on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Doing test deploy to Pinata
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Pinata deploy action step
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'web'
          path: './.github/workflows/site2test'
          pinata-api-key: ${{6388b006aa66fa490c07}}
          pinata-secret-api-key: ${{995eba33e933d524a8be50b348663d6f72b8c4ad7ae06d9a7b3dc042cb614869}}
          verbose: true
          remove-old: false
      # Use the output from the `deploy` step
      - name: Get the output hash
        run: echo "The hash was ${{ steps.deploy.outputs.hash }}"